# Generated by Django 6.0.2 on 2026-02-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_blood_group_patientmedicalprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.BigIntegerField()),
                ('otp', models.CharField(max_length=10)),
                ('purpose', models.CharField(choices=[('patient_register', 'Patient Register'), ('clinic_register', 'Clinic Register')], default='patient_register', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OTP Log',
                'verbose_name_plural': 'OTP Logs',
                'db_table': 'otp_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
