# Generated by Django 6.0.2 on 2026-02-25 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPasswordLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.BigIntegerField()),
                ('temp_password', models.CharField(max_length=20)),
                ('is_used', models.BooleanField(default=False, help_text='Set to True once the member completes onboarding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='Clinic owner who triggered the auto-registration', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_passwords_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temp Password Log',
                'verbose_name_plural': 'Temp Password Logs',
                'db_table': 'temp_password_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
