# Generated by Django 6.0.2 on 2026-02-24 03:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('clinic_type', models.CharField(choices=[('clinic', 'Clinic'), ('hospital', 'Hospital'), ('diagnostic_center', 'Diagnostic Center'), ('polyclinic', 'Polyclinic')], default='clinic', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinic/logos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clinic',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_role', models.CharField(choices=[('doctor', 'Doctor'), ('lab_member', 'Lab Member'), ('receptionist', 'Receptionist')], default='doctor', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive')], default='pending', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('invite_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this member (e.g. visiting doctor)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clinic_member',
                'ordering': ['-created_at'],
            },
        ),
    ]
