# Generated by Django 6.0.2 on 2026-02-24 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='owner',
            field=models.ForeignKey(help_text='The clinic owner/admin user (role = IS_CLINIC_OWNER)', on_delete=django.db.models.deletion.CASCADE, related_name='owned_clinics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicmember',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_clinic_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicmember',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clinic.clinic'),
        ),
        migrations.AddField(
            model_name='clinicmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clinicmember',
            unique_together={('clinic', 'user')},
        ),
    ]
