# Generated by Django 6.0.2 on 2026-02-24 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicTimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.PositiveSmallIntegerField(default=15, help_text='Duration of each appointment slot in minutes')),
                ('max_appointments', models.PositiveSmallIntegerField(default=20, help_text='Max appointments in this time window')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='clinic.clinic')),
            ],
            options={
                'db_table': 'clinic_time_slot',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('clinic', 'day_of_week', 'start_time')},
            },
        ),
    ]
