# Generated by Django 6.0.2 on 2026-02-25 05:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_clinictimeslot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicAdmissionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_name', models.CharField(help_text="Human-readable name, e.g. 'Aadhar Card', 'CBC Blood Report'", max_length=200)),
                ('document_type', models.CharField(choices=[('id_proof', 'ID Proof (Aadhar, PAN, Passport)'), ('insurance', 'Insurance / TPA Card'), ('prescription', 'Prescription / Referral Letter'), ('lab_report', 'Lab / Blood Report'), ('imaging', 'Imaging / X-Ray / MRI / CT Scan'), ('vaccination', 'Vaccination Record'), ('discharge_summary', 'Previous Discharge Summary'), ('other', 'Other')], default='other', max_length=50)),
                ('is_mandatory', models.BooleanField(default=True, help_text='True = patient must bring this; False = recommended but optional')),
                ('notes', models.TextField(blank=True, help_text="Additional instructions for the patient, e.g. 'original + 2 photocopies'", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_documents', to='clinic.clinic')),
            ],
            options={
                'db_table': 'clinic_admission_document',
                'ordering': ['-is_mandatory', 'document_type', 'document_name'],
            },
        ),
    ]
