# Generated by Django 6.0.2 on 2026-02-27 21:07

from django.db import migrations


def backfill_member_role(apps, schema_editor):
    """
    Any ClinicMember row with a blank member_role was created via the Django
    admin before the field was enforced at the API layer.  The model default
    is 'doctor', so backfill those rows accordingly.
    """
    ClinicMember = apps.get_model('clinic', 'ClinicMember')
    updated = ClinicMember.objects.filter(member_role='').update(member_role='doctor')
    if updated:
        print(f"\n  Backfilled {updated} ClinicMember row(s) with member_role='' → 'doctor'")


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_clinicadmissiondocument'),
    ]

    operations = [
        migrations.RunPython(backfill_member_role, migrations.RunPython.noop),
    ]
