# Generated by Django 6.0.2 on 2026-02-24 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_access_log',
                'ordering': ['-accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('purpose', models.TextField(blank=True, help_text='Why the doctor is requesting access', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for indefinite access', null=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document_consent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('prescription', 'Prescription'), ('lab_report', 'Lab Report'), ('scan', 'Scan / Imaging'), ('discharge_summary', 'Discharge Summary'), ('vaccination', 'Vaccination Record'), ('insurance', 'Insurance Document'), ('other', 'Other')], default='other', max_length=50)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('description', models.TextField(blank=True, null=True)),
                ('uploaded_by_role', models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='appointments.appointment')),
            ],
            options={
                'db_table': 'document',
                'ordering': ['-created_at'],
            },
        ),
    ]
