# Generated by Django 6.0.2 on 2026-02-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_by_role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('lab_member', 'Lab Member')], default='patient', max_length=20),
        ),
    ]
