# Generated by Django 6.0.2 on 2026-02-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(db_index=True)),
                ('appointment_time', models.TimeField()),
                ('appointment_type', models.CharField(choices=[('first_visit', 'First Visit'), ('follow_up', 'Follow Up')], default='first_visit', max_length=20)),
                ('mode', models.CharField(choices=[('in_clinic', 'In Clinic'), ('video', 'Video Consultation')], default='in_clinic', max_length=20)),
                ('reason', models.TextField(blank=True, help_text="Patient's reason for visit / chief complaint", null=True)),
                ('notes', models.TextField(blank=True, help_text="Doctor's notes after the appointment", null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='pending', max_length=20)),
                ('fee_charged', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_paid', models.BooleanField(default=False)),
                ('cancelled_by', models.CharField(blank=True, max_length=50, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appointment',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
    ]
