# Generated by Django 6.0.2 on 2026-02-24 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialty', models.CharField(choices=[('general_medicine', 'General Medicine'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT'), ('psychiatry', 'Psychiatry'), ('dentistry', 'Dentistry'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('oncology', 'Oncology'), ('urology', 'Urology'), ('other', 'Other')], default='general_medicine', max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('biography', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, help_text='Comma-separated, e.g. English, Hindi', max_length=200, null=True)),
                ('first_visit_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('follow_up_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('offers_video_consultation', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'doctor_profile',
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_duration_minutes', models.PositiveIntegerField(default=15, help_text='Duration of each appointment slot in minutes')),
                ('max_patients', models.PositiveIntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_slots', to='clinic.clinic')),
            ],
            options={
                'db_table': 'doctor_availability',
                'ordering': ['day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_leaves', to='clinic.clinic')),
            ],
            options={
                'db_table': 'doctor_leave',
                'ordering': ['-start_date'],
            },
        ),
    ]
